### ISSUE TITLE
Changes to workshop page

### ISSUE THREAD

**Issue by vansteph** [monahton/2022-07-05-vu-online#1]
@monahton sorry for creating an issue, please change :

- Vrije Universiteit -> Vrije Universiteit **Amsterdam**
- 9:00 am - 1:00 pm CET -> 9:**3**0 am - 1:**3**0 pm CE**S**T
- the schedule for the workshop must be edited accordingly, we start at 9:30 every day and close at 13:30
- our etherpad for collaborative notes is here: https://pad.carpentries.org/2022-07-05-vu-online

Name of helpers:

- Cristoforo Grasso
- Elisa Rodenburg
- Max Paulus
- Koen Leuveld
- Sophie Arnoult
- Meron Vermaas
- Stephanie van de Sandt

Thank you!

**Comment by monahton** [comment]
@vansteph all fixed now
You're welcome!
